[logging]
level = "debug"
output = "stdout"

[profiler]
enabled = true
bind = ":6060"

[servers.default]
bind = "127.0.0.1:5555"
protocol = "udp"
client_idle_timeout = "120s"
backend_idle_timeout = "120s"
balance = "roundrobin"

[servers.default.udp]
max_requests = 0
max_responses = 0

[servers.default.discovery]
kind = "static"
static_list = [
       "127.0.0.1:5001",
]
